# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Flake8

on: 
  push:
    paths:
      - '**.py'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        
    - name: Lint with flake8
      run: |
        echo "FLAKE_ERRORS=$(flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --output-file ./flake8.log)" >> $GITHUB_ENV

    - name: Create Pylint Badge
      uses: LucasWolfgang/dynamic-badges-action@master
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 344598a4a0f7b92a7889d998e33417c4
        filename: flake8.json
        label: Pylint
        message: errors
        minColorRange: 0
        maxColorRange: 50
        valColorRange: ${{ env.FLAKE_ERRORS }}
