# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pytests

on: 
  push:
    paths:
      - '**.py'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pytest
        
    - name: Test with pytest
      run: |
        pytest >> ./pytest.log
        echo "PYTEST_MAX=$(sed -n 's/collected \([0-9]*\) items/\1/p' ./pytest.log)" >> $GITHUB_ENV
        echo "PYTEST_MIN=$(echo "$PYTEST_MAX - 2" | bc) " >> $GITHUB_ENV
        echo "PYTEST_SCORE=$(sed -n 's/^===.* \([0-9]*\) passed in.*===/\1/p' ./pytest.log)" >> $GITHUB_ENV
        
    - name: Create Pylint Badge
      uses: LucasWolfgang/dynamic-badges-action@master
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 344598a4a0f7b92a7889d998e33417c4
        filename: pytest.json
        label: Pylint
        message: ${{ env.PYTEST_SCORE }} / ${{ env.PYTEST_MAX }} tests
