name: regression

on: 
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install pylint pytest pytest-qt flake8 .
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

        
    - name: Lint with pylint
      run: |
        pylint qas_editor --rcfile=$(git ls-files '.pylintrc') --output-format=text | tee ./pylint.log || pylint-exit $?
        echo "PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint.log)" >> $GITHUB_ENV
      
    - name: Lint with flake8
      run: |
        echo "FLAKE_ERRORS=$(flake8 qas_editor --count --exit-zero --statistics --output-file ./flake8.log)" >> $GITHUB_ENV

    - name: Test with pytest
      run: |
        pytest ./test_lib | tee ./pytest.log
        echo "PYTEST_MAX=$(sed -n 's/collected \([0-9]*\) items/\1/p' ./pytest.log)" >> $GITHUB_ENV
        echo "PYTEST_SCORE=$(sed -n 's/^===.* \([0-9]*\) passed.*===/\1/p' ./pytest.log)" >> $GITHUB_ENV
      continue-on-error: true

    - name: Create Pylint Badge
      uses: LucasWolfgang/dynamic-badges-action@master
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 344598a4a0f7b92a7889d998e33417c4
        filename: pylint_${{ matrix.python-version }}.json
        label: Pylint
        message: ${{ env.PYLINT_SCORE }} / 10.0 points
        minColorRange: 6
        maxColorRange: 10
        valColorRange: ${{ env.PYLINT_SCORE }}
      continue-on-error: true
    
    - name: Create Flake8 Badge
      uses: LucasWolfgang/dynamic-badges-action@master
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 344598a4a0f7b92a7889d998e33417c4
        filename: flake8_${{ matrix.python-version }}.json
        label: Flake8
        message: ${{ env.FLAKE_ERRORS }} errors
        minColorRange: 0
        maxColorRange: 50
        valColorRange: ${{ env.FLAKE_ERRORS }}
        invertColorRange: 1
      continue-on-error: true
    
    - name: Create Pytest Badge
      uses: LucasWolfgang/dynamic-badges-action@master
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 344598a4a0f7b92a7889d998e33417c4
        filename: pytest_${{ matrix.python-version }}.json
        label: Pytest
        message: ${{ env.PYTEST_SCORE }} / ${{ env.PYTEST_MAX }} tests
        minColorRange: 13
        maxColorRange: ${{ env.PYTEST_MAX }} 
        valColorRange: ${{ env.PYTEST_SCORE }}
    
