name: regression

on: 
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        
    - name: Analysing the code with pylint
      run: |
        pylint qas_editor --rcfile=$(git ls-files '.pylintrc') --output-format=text | tee ./pylint.log || pylint-exit $?
        echo "::set-env PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint.log)"
        
    - name: Create Awesome Badge
      uses: LucasWolfgang/dynamic-badges-action@master
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: <gist-ID>
        filename: test.json
        label: Hello
        message: ${{ PYLINT_SCORE }}
        minColorRange: 6
        maxColorRange: 10

    - name: Test with pytest
      run: |
        pytest

